# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc "Run beta build and upload to play store"
 lane :preProd do
   gradle(task: 'clean')
    gradle(task: 'assemble', flavor: "preProd", build_type: 'Release',
       properties: {
           "versionCode" => ENV['VERSION_CODE'],
           "versionName" => ENV['VERSION_NAME'],
           "hashSalt" => ENV['HASH_SALT'],
           "android.injected.signing.store.file" => "app/deploytestkeystore.jks",
           "android.injected.signing.store.password" => "admin123",
           "android.injected.signing.key.alias" => "deploy"
         }
              )



     upload_to_play_store(track: 'beta')
 end

desc "Run production build and upload to play store"
 lane :prod do
   gradle(task: 'clean')
    gradle(task: 'assemble', flavor: "prod", build_type: 'Release',
       properties: {
           "versionCode" => ENV['VERSION_CODE'],
           "versionName" => ENV['VERSION_NAME'],
           "hashSalt" => ENV['HASH_SALT'],
           "android.injected.signing.store.file" => "app/deploytestkeystore.jks",
           "android.injected.signing.store.password" => "admin123",
           "android.injected.signing.key.alias" => "deploy"
         }
              )



     upload_to_play_store(track:production)
 end

